name: Jest CI

on:
  - pull_request

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: yarn

      - name: Run Unit Tests
        run: yarn test

      - name: Run Typecheck
        run: yarn typecheck
